from sf.doom.wrappers.scenario_wrappers.gathering_reward_shaping import DoomGatheringRewardShaping
from sf.doom.wrappers.scenario_wrappers.pitfall_reward_shaping import DoomPitfallRewardShaping
from sf.doom.wrappers.scenario_wrappers.mwh_reward_shaping import DoomMWHRewardShaping