[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "COMRAD"
version = "0.1.0"
description = "comrad"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26.4,<2.0",
    "gymnasium>=0.29.1",
    "pettingzoo>=1.25.0",
    "vizdoom>=1.2.4",
    "opencv-python>=4.11.0",
    "pygame>=2.6.1",
    "pre-commit>=4.5.1",
    "pynput>=1.8.1",
]

[project.optional-dependencies]
sample-factory = [
    "torch>=2.9.0",
    "wandb>=0.22.1",
    "tensorboard>=2.20.0",
    "colorlog>=6.10.1",
    "signal-slot-mp>=1.0.5",
    "faster-fifo>=1.5.2",
    "filelock>=3.19.1",
    "psutil>=7.1.0",
    "huggingface_hub>=0.36.0",
    "scipy>=1.16.3",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["sf*", "sample_factory*"]

[tool.ruff]
line-length = 120
extend-exclude = ["vizdoom.pyi"]

[tool.ruff.lint]
ignore = ["E701"]
